export const myColors = {
  primaryColor: "#58A4B0",
  secondaryColor: "#1B1B1E",
  tertiaryColor: "#F3DE8A",
  lightGrayColor: "#D8DBE2",
  darkGrayColor: "#373F51",
  redColor: "#FB3640",
  whiteColor: "#F9F8F8",
};

export const myFontFamilies = {
  regular: "NotoRegular",
  bold: "NotoBold",
};

export const myFontSizes = {
  xs: 12,
  small: 14,
  regular: 16,
  large: 20,
  xl: 24,
  xxl: 32,
};

export const myLogos = {
  amazon: "logo-amazon",
  apple: "logo-apple",
  bitcoin: "logo-bitcoin",
  chrome: "logo-chrome",
  dribbble: "logo-dribbble",
  dropbox: "logo-dropbox",
  facebook: "logo-facebook",
  firefox: "logo-firefox",
  flickr: "logo-flickr",
  github: "logo-github",
  google: "logo-google",
  gmail: "logo-google",
  html: "logo-html5",
  instagram: "logo-instagram",
  javascript: "logo-javascript",
  linkedin: "logo-linkedin",
  microsoft: "logo-windows",
  pinterest: "logo-pinterest",
  playstation: "logo-playstation",
  reddit: "logo-reddit",
  skype: "logo-skype",
  slack: "logo-slack",
  snapchat: "logo-snapchat",
  stackoverflow: "logo-stackoverflow",
  steam: "logo-steam",
  tumblr: "logo-tumblr",
  twitch: "logo-twitch",
  twitter: "logo-twitter",
  vimeo: "logo-vimeo",
  whatsapp: "logo-whatsapp",
  windows: "logo-windows",
  wordpress: "logo-wordpress",
  xbox: "logo-xbox",
  yahoo: "logo-yahoo",
  youtube: "logo-youtube",
};
